version: '3.8'

services:
    web:
        image: ghcr.io/rosmis/spk_back/spk_api:dev
        ports:
            - "80:80"
            - "443:443"
            - "443:443/udp"
        volumes:
            - './.env:/var/www/html/.env'
            - caddy_data:/data
            - caddy_config:/config
        networks:
            - laravel_network
        depends_on:
          db:
              condition: service_healthy
        entrypoint: ["/entrypoint.sh"]

    db:
        image: mysql/mysql-server:8.0
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        volumes:
            - 'spk_db:/var/lib/mysql'
        networks:
            - laravel_network
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - -p${DB_PASSWORD}
            retries: 3
            timeout: 5s

    phpmyadmin:
        image: phpmyadmin:latest
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        networks:
            - laravel_network
        depends_on:
            db:
                condition: service_healthy

networks:
    laravel_network:
        driver: bridge

volumes:
    spk_db:
    caddy_data:
    caddy_config:
