services:
    web:
        build:
            context: ./
            dockerfile: ./.docker/Dockerfile.dev
        volumes:
            - './.env:/var/www/html/.env'
            - .:/app
        ports:
            - '80:80'
        networks:
            - laravel_network
        depends_on:
          db:
              condition: service_healthy
        entrypoint: ["/entrypoint.sh"]
    db:
        image: mysql/mysql-server:8.0
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        volumes:
            - 'sail-mysql:/var/lib/mysql'
        networks:
            - laravel_network
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - -p${DB_PASSWORD}
            retries: 3
            timeout: 5s

    phpmyadmin:
        image: phpmyadmin:latest
        ports:
            - '8080:80'
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        depends_on:
            db:
                condition: service_healthy
        networks:
            - laravel_network
networks:
    laravel_network:
        driver: bridge

volumes:
    sail-mysql: