services:
  init:
    build:
      dockerfile: Dockerfile.dev
    command: php artisan migrate
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
  php:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      SERVER_NAME: ":80"
    ports:
      - 80:80
    depends_on:
      init:
        condition: service_completed_successfully
    volumes:
      - .:/app
  db:
    image: 'mysql/mysql-server:8.0'
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - 'db_data:/var/lib/mysql'
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - '-p${DB_PASSWORD}'
      retries: 3
      timeout: 5s

volumes:
  db_data: