services:
    web:
        image: ghcr.io/rosmis/spk_back/spk_api:dev
        volumes:
            - './.env:/app/.env'
            - caddy_data:/data
            - caddy_config:/config
        tty: true
        ports:
            - '80:80'
            - "443:443"
            - "443:443/udp"
        networks:
            - laravel_network
        depends_on:
          db:
              condition: service_healthy
    queue:
        image: ghcr.io/rosmis/spk_back/spk_api:dev
        volumes:
            - './.env:/app/.env'
        networks:
            - laravel_network
        depends_on:
          web:
              condition: service_healthy
        tty: true
        entrypoint: ["/queue-entrypoint.sh"]
    db:
        image: mysql/mysql-server:8.0
        ports:
            - 127.0.0.1:3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        volumes:
            - 'sail-mysql:/var/lib/mysql'
        networks:
            - laravel_network
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - -p${DB_PASSWORD}
            retries: 3
            timeout: 5s
networks:
    laravel_network:
        driver: bridge

volumes:
    sail-mysql:
    caddy_data:
    caddy_config: