#!/usr/bin/env bash

echo "Running initialization tasks..."

# Ensure .env file is present
if [ ! -f /var/www/html/.env ]; then
    echo "Error: .env file not found at /var/www/html/.env"
    exit 1
fi

# Set correct permissions for storage and cache directories
chown -R 1000:1000 storage/
chmod -R 775 storage/
chown -R 1000:1000 bootstrap/cache/

# Run Laravel commands
php artisan config:clear
php artisan key:generate
php artisan migrate --force

if [ "$SUPERVISOR_PHP_USER" != "root" ] && [ "$SUPERVISOR_PHP_USER" != "sail" ]; then
    echo "You should set SUPERVISOR_PHP_USER to either 'sail' or 'root'."
    exit 1
fi

if [ ! -z "$WWWUSER" ]; then
    usermod -u $WWWUSER sail
fi

if [ ! -d /.composer ]; then
    mkdir /.composer
fi

chmod -R ugo+rw /.composer

if [ $# -gt 0 ]; then
    if [ "$SUPERVISOR_PHP_USER" = "root" ]; then
        exec "$@"
    else
        exec gosu $WWWUSER "$@"
    fi
else
    exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
fi
