#!/usr/bin/env bash

log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1"
}

log "Starting container initialization..."

if [ "$SUPERVISOR_PHP_USER" != "root" ] && [ "$SUPERVISOR_PHP_USER" != "sail" ]; then
    log "Error: SUPERVISOR_PHP_USER should be set to either 'sail' or 'root'."
    exit 1
fi

if [ ! -z "$WWWUSER" ]; then
    log "Updating sail user ID to $WWWUSER"
    usermod -u $WWWUSER sail
fi

if [ ! -d /.composer ]; then
    log "Creating .composer directory"
    mkdir /.composer
fi

log "Setting permissions for .composer directory"
chmod -R ugo+rw /.composer

# Start supervisord
log "Starting supervisord"
/usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf &

# Run the initialization script in the background
log "Running initialization script"
/usr/local/bin/initialize-app.sh &

# Keep the container running
tail -f /dev/null