name: Deploy Laravel Docker Image

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Build Docker image with Buildx
        run: |
          docker buildx build -t ghcr.io/${{ github.repository }}/spk_api:dev \
            --file ./.docker/prod/Dockerfile.prod \
            --no-cache \
            --progress=plain \
            --push \
            .

      - name: Verify image push
        run: |
          echo "Image successfully pushed to ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:dev"

      - name: Deploy to production
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USERNAME }}
          key: ${{ secrets.PROD_SSH_KEY }}
          script: |
            cd spk/
            docker compose pull web queue
            docker compose up -d --force-recreate web queue
